[package]
name = "deputy"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
dotenv = "0.15.0"
glob = "0.3.2"
time = { version = "0.3.39", features = ["formatting"] }
